#!/bin/bash
rm -f $1.epub
cd $1
zip -q0X "../$1.epub" mimetype
zip -qXr9D "../$1.epub" * -x "*.svn*" -x "*~" -x "*.hg*" -x "*.swp" -x "*.DS_Store"
java -jar ../bin/epubcheck-3.0-RC-1.jar ../$1.epub

cd ..
kindlegen ./book/OEBPS/content.opf -o 脂砚斋重评石头记.mobi
cp ./book/OEBPS/*.mobi ./
rm -r ./book/OEBPS/*.mobi


